// <auto-generated />
using McDonalds.Kiosk.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McDonalds.Kiosk.DatabaseContext.Migrations.MySqlMigrations
{
    [DbContext(typeof(KioskMySqlContext))]
    [Migration("20200123223239_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("McDonalds.Kiosk.DatabaseContext.Entities.DrinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AmountInMilliliters")
                        .HasColumnType("int");

                    b.Property<bool>("IsHot")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Drink");
                });

            modelBuilder.Entity("McDonalds.Kiosk.DatabaseContext.Entities.FoodEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FoodSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("McDonalds.Kiosk.DatabaseContext.Entities.ProductIdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductId");
                });

            modelBuilder.Entity("McDonalds.Kiosk.DatabaseContext.Entities.DrinkEntity", b =>
                {
                    b.HasOne("McDonalds.Kiosk.DatabaseContext.Entities.ProductIdEntity", "ProductId")
                        .WithOne("Drink")
                        .HasForeignKey("McDonalds.Kiosk.DatabaseContext.Entities.DrinkEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McDonalds.Kiosk.DatabaseContext.Entities.FoodEntity", b =>
                {
                    b.HasOne("McDonalds.Kiosk.DatabaseContext.Entities.ProductIdEntity", "ProductId")
                        .WithOne("Food")
                        .HasForeignKey("McDonalds.Kiosk.DatabaseContext.Entities.FoodEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
